version: '3'
services:
  nginx:
    image: nginx
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    command: nginx -g 'daemon off;' -c /etc/nginx/nginx.conf
    ports:
      - 80:80
  ttc-backend:
    image: zhaoyim/ttc-backend
  draw-something:
    image: zhaoyim/draw-something
networks:
  default:
    driver: custom-driver-1